# kubectl apply -f mysql-dep.yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  type: ClusterIP       # ClusterIP, LoadBalancer, NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8.0.34-debian
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        # Add secret
        env:
        - name: MYSQL_USER
          valueFrom: 
            secretKeyRef:
              name: mysql-secret
              key: username     
        - name: MYSQL_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mysql-secret
              key: password              
        - name: MYSQL_DATABASE
          valueFrom: 
            configMapKeyRef:
              name: mysql-configmap
              key: database
---