apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: ahmadooof/mysql:1.0.8
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-chat-host
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-school-host
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  type: NodePort
