apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  name: react
  labels:
    app: react
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: react
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - image: ahmadooof/react
        imagePullPolicy: Always
        name: react
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: react
  name: react
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 7777           # optional service port
    protocol: TCP
    targetPort: 80      # port of the pod
  selector:
    app: react
  type: ClusterIP       # ClusterIP, LoadBalancer, NodePort
  
---

# without TLs
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: react
#   namespace: default
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: techwithahmad.com
#     http:
#       paths:
#       - backend:
#           service:
#             name: react
#             port:
#               number: 7777
#         path: /
#         pathType: Prefix

---
# with TLS
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - techwithahmad.com
    secretName: quickstart-example-tls
  rules:
  - host: techwithahmad.com
    http:
      paths:
      - backend:
          service:
            name: react
            port:
              number: 7777
        path: /
        pathType: Prefix

---

