apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: kubernetes.io/basic-auth
stringData:
# echo -n 'ahmad' | base64
# [Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes("ahmad")) this is applied
  username: YQBoAG0AYQBkAA==
#  echo -n 'root' | base64
# [Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes("root")) this is applied
  password: cgBvAG8AdAA=

# kubectl apply -f mysql-secret.yaml