apiVersion: v1
kind: ConfigMap
metadata:
  name: app1-configmap
data:
  HOST: mysql-chat-host
  DATABASE: chat

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: app2-configmap
data:
  HOST: mysql-school-host
  DATABASE: school