apiVersion: v1
kind: Service
metadata:
  name: wireguard-service
spec:
  type: NodePort
  selector:
    app: wireguard-pod
  ports:
    - protocol: UDP
      port: 51820
      targetPort: 51820
      nodePort: 30000