apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data: 
  host: mysql-service
  database: school


# this is used by expressjs to make connection to mysql service

# kubectl apply -f mysql-con.yaml