apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
type: kubernetes.io/basic-auth
data:
  username: base64
  password: base64

# on windows:
# [Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes("base64secret"))
